kind: pipeline
name: default

steps:
- name: test
  image: node
  environment:
     CC_TEST_REPORTER_ID:
         from_secret: cc_token
  commands:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > "cc-test-reporter"
  - chmod +x "cc-test-reporter"
  - npm install
  - npm test
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json coverage/lcov.info
  - ./cc-test-reporter upload-coverage
  when:
    event:
    - pull_request

